##WIA 1007 Tutorial 3
##Part 1-Google Colab and Python

In [ ]:
import numpy as np

In [ ]:
#1. Create a numpy array of size 2 x 2
a = np.array([[1,2],[3,4]])
print("NumPy array of size 2 x 2:")
print(a)

NumPy array of size 2 x 2:
[[1 2]
 [3 4]]


In [ ]:
#2. Create a random numpy array of size 3 x 4
b = np.random.random((3,4))
print("Random NumPy array of size 3 x 4:")
print(b)

Random NumPy array of size 3 x 4:
[[0.40427346 0.81772429 0.54332482 0.85151761]
 [0.6621132  0.38329761 0.7241598  0.59343786]
 [0.84659372 0.27439599 0.17802832 0.68998322]]


In [ ]:
#3. Create a numpy array of ones and a numpy array of zeroes
c = np.ones((2,2))
d = np.zeros((2,2))
print("NumPy array of ones:")
print(c)
print()
print("NumPy array of zeros:")
print(d)

NumPy array of ones:
[[1. 1.]
 [1. 1.]]

NumPy array of zeros:
[[0. 0.]
 [0. 0.]]


In [ ]:
#4. Create a random numpy array of size 6x3 and transpose it
e = np.random.random((6,3))
print ("Random NumPy array of size 6 x 3:")
print(e)
print()
print("Transposed NumPy array:")
print(e.T)


Random NumPy array of size 6 x 3:
[[0.18574964 0.81307519 0.68210249]
 [0.47251668 0.00622065 0.07425304]
 [0.38390866 0.38150013 0.61987774]
 [0.51948657 0.16313847 0.95024868]
 [0.08270674 0.53207503 0.58108672]
 [0.27388092 0.66743766 0.65935069]]

Transposed NumPy array:
[[0.18574964 0.47251668 0.38390866 0.51948657 0.08270674 0.27388092]
 [0.81307519 0.00622065 0.38150013 0.16313847 0.53207503 0.66743766]
 [0.68210249 0.07425304 0.61987774 0.95024868 0.58108672 0.65935069]]


In [ ]:
#5. Create two random numpy array of size n x p and p x m and then compute the dot product
n = 1
p = 2
m = 3
f = np.random.random((n, p))
g = np.random.random((p, m))
dot_product = np.dot(A, B)

print("Matrix A (n x p):")
print(f)
print()
print("Matrix B (p x m):")
print(g)
print()
print("Dot Product (A · B):")
print(dot_product)

Matrix A (n x p):
[[0.90694366 0.81291265]]

Matrix B (p x m):
[[0.14459195 0.29220513 0.71849858]
 [0.31330343 0.98421192 0.24883996]]

Dot Product (A · B):
[[0.98107703 0.95296236 0.60610317]]
